version: '3'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.nodejs
    ports:
      - "3000:3000"
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - server